/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollabrationRouteRouteImport } from './routes/collabration/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollabrationIndexRouteImport } from './routes/collabration/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as CollabrationManufacturingIndexRouteImport } from './routes/collabration/manufacturing/index'
import { Route as CollabrationInventoryIndexRouteImport } from './routes/collabration/inventory/index'
import { Route as CollabrationCapacityIndexRouteImport } from './routes/collabration/capacity/index'
import { Route as CollabrationAccessoriesIndexRouteImport } from './routes/collabration/accessories/index'
import { Route as CollabrationInventoryAddRouteImport } from './routes/collabration/inventory/add'
import { Route as CollabrationAccessoriesAddRouteImport } from './routes/collabration/accessories/add'

const CollabrationRouteRoute = CollabrationRouteRouteImport.update({
  id: '/collabration',
  path: '/collabration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabrationIndexRoute = CollabrationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabrationRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CollabrationManufacturingIndexRoute =
  CollabrationManufacturingIndexRouteImport.update({
    id: '/manufacturing/',
    path: '/manufacturing/',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)
const CollabrationInventoryIndexRoute =
  CollabrationInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)
const CollabrationCapacityIndexRoute =
  CollabrationCapacityIndexRouteImport.update({
    id: '/capacity/',
    path: '/capacity/',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)
const CollabrationAccessoriesIndexRoute =
  CollabrationAccessoriesIndexRouteImport.update({
    id: '/accessories/',
    path: '/accessories/',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)
const CollabrationInventoryAddRoute =
  CollabrationInventoryAddRouteImport.update({
    id: '/inventory/add',
    path: '/inventory/add',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)
const CollabrationAccessoriesAddRoute =
  CollabrationAccessoriesAddRouteImport.update({
    id: '/accessories/add',
    path: '/accessories/add',
    getParentRoute: () => CollabrationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collabration': typeof CollabrationRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/otp': typeof AuthOtpRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collabration/': typeof CollabrationIndexRoute
  '/collabration/accessories/add': typeof CollabrationAccessoriesAddRoute
  '/collabration/inventory/add': typeof CollabrationInventoryAddRoute
  '/collabration/accessories/': typeof CollabrationAccessoriesIndexRoute
  '/collabration/capacity/': typeof CollabrationCapacityIndexRoute
  '/collabration/inventory/': typeof CollabrationInventoryIndexRoute
  '/collabration/manufacturing/': typeof CollabrationManufacturingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/otp': typeof AuthOtpRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collabration': typeof CollabrationIndexRoute
  '/collabration/accessories/add': typeof CollabrationAccessoriesAddRoute
  '/collabration/inventory/add': typeof CollabrationInventoryAddRoute
  '/collabration/accessories': typeof CollabrationAccessoriesIndexRoute
  '/collabration/capacity': typeof CollabrationCapacityIndexRoute
  '/collabration/inventory': typeof CollabrationInventoryIndexRoute
  '/collabration/manufacturing': typeof CollabrationManufacturingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/collabration': typeof CollabrationRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/collabration/': typeof CollabrationIndexRoute
  '/collabration/accessories/add': typeof CollabrationAccessoriesAddRoute
  '/collabration/inventory/add': typeof CollabrationInventoryAddRoute
  '/collabration/accessories/': typeof CollabrationAccessoriesIndexRoute
  '/collabration/capacity/': typeof CollabrationCapacityIndexRoute
  '/collabration/inventory/': typeof CollabrationInventoryIndexRoute
  '/collabration/manufacturing/': typeof CollabrationManufacturingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collabration'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/collabration/'
    | '/collabration/accessories/add'
    | '/collabration/inventory/add'
    | '/collabration/accessories/'
    | '/collabration/capacity/'
    | '/collabration/inventory/'
    | '/collabration/manufacturing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/collabration'
    | '/collabration/accessories/add'
    | '/collabration/inventory/add'
    | '/collabration/accessories'
    | '/collabration/capacity'
    | '/collabration/inventory'
    | '/collabration/manufacturing'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/collabration'
    | '/_auth/forgot-password'
    | '/_auth/otp'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/collabration/'
    | '/collabration/accessories/add'
    | '/collabration/inventory/add'
    | '/collabration/accessories/'
    | '/collabration/capacity/'
    | '/collabration/inventory/'
    | '/collabration/manufacturing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CollabrationRouteRoute: typeof CollabrationRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collabration': {
      id: '/collabration'
      path: '/collabration'
      fullPath: '/collabration'
      preLoaderRoute: typeof CollabrationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collabration/': {
      id: '/collabration/'
      path: '/'
      fullPath: '/collabration/'
      preLoaderRoute: typeof CollabrationIndexRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/collabration/manufacturing/': {
      id: '/collabration/manufacturing/'
      path: '/manufacturing'
      fullPath: '/collabration/manufacturing/'
      preLoaderRoute: typeof CollabrationManufacturingIndexRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/inventory/': {
      id: '/collabration/inventory/'
      path: '/inventory'
      fullPath: '/collabration/inventory/'
      preLoaderRoute: typeof CollabrationInventoryIndexRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/capacity/': {
      id: '/collabration/capacity/'
      path: '/capacity'
      fullPath: '/collabration/capacity/'
      preLoaderRoute: typeof CollabrationCapacityIndexRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/accessories/': {
      id: '/collabration/accessories/'
      path: '/accessories'
      fullPath: '/collabration/accessories/'
      preLoaderRoute: typeof CollabrationAccessoriesIndexRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/inventory/add': {
      id: '/collabration/inventory/add'
      path: '/inventory/add'
      fullPath: '/collabration/inventory/add'
      preLoaderRoute: typeof CollabrationInventoryAddRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/accessories/add': {
      id: '/collabration/accessories/add'
      path: '/accessories/add'
      fullPath: '/collabration/accessories/add'
      preLoaderRoute: typeof CollabrationAccessoriesAddRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CollabrationRouteRouteChildren {
  CollabrationIndexRoute: typeof CollabrationIndexRoute
  CollabrationAccessoriesAddRoute: typeof CollabrationAccessoriesAddRoute
  CollabrationInventoryAddRoute: typeof CollabrationInventoryAddRoute
  CollabrationAccessoriesIndexRoute: typeof CollabrationAccessoriesIndexRoute
  CollabrationCapacityIndexRoute: typeof CollabrationCapacityIndexRoute
  CollabrationInventoryIndexRoute: typeof CollabrationInventoryIndexRoute
  CollabrationManufacturingIndexRoute: typeof CollabrationManufacturingIndexRoute
}

const CollabrationRouteRouteChildren: CollabrationRouteRouteChildren = {
  CollabrationIndexRoute: CollabrationIndexRoute,
  CollabrationAccessoriesAddRoute: CollabrationAccessoriesAddRoute,
  CollabrationInventoryAddRoute: CollabrationInventoryAddRoute,
  CollabrationAccessoriesIndexRoute: CollabrationAccessoriesIndexRoute,
  CollabrationCapacityIndexRoute: CollabrationCapacityIndexRoute,
  CollabrationInventoryIndexRoute: CollabrationInventoryIndexRoute,
  CollabrationManufacturingIndexRoute: CollabrationManufacturingIndexRoute,
}

const CollabrationRouteRouteWithChildren =
  CollabrationRouteRoute._addFileChildren(CollabrationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CollabrationRouteRoute: CollabrationRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
