/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollabrationRouteRouteImport } from './routes/collabration/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as CollabrationAuthSignInRouteImport } from './routes/collabration/_auth/sign-in'
import { Route as CollabrationAuthOtpRouteImport } from './routes/collabration/_auth/otp'

const CollabrationRouteRoute = CollabrationRouteRouteImport.update({
  id: '/collabration',
  path: '/collabration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CollabrationAuthSignInRoute = CollabrationAuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => CollabrationRouteRoute,
} as any)
const CollabrationAuthOtpRoute = CollabrationAuthOtpRouteImport.update({
  id: '/_auth/otp',
  path: '/otp',
  getParentRoute: () => CollabrationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collabration': typeof CollabrationRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collabration/otp': typeof CollabrationAuthOtpRoute
  '/collabration/sign-in': typeof CollabrationAuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collabration': typeof CollabrationRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collabration/otp': typeof CollabrationAuthOtpRoute
  '/collabration/sign-in': typeof CollabrationAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/collabration': typeof CollabrationRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/collabration/_auth/otp': typeof CollabrationAuthOtpRoute
  '/collabration/_auth/sign-in': typeof CollabrationAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collabration'
    | '/forgot-password'
    | '/sign-up'
    | '/collabration/otp'
    | '/collabration/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collabration'
    | '/forgot-password'
    | '/sign-up'
    | '/collabration/otp'
    | '/collabration/sign-in'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/collabration'
    | '/_auth/forgot-password'
    | '/_auth/sign-up'
    | '/collabration/_auth/otp'
    | '/collabration/_auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CollabrationRouteRoute: typeof CollabrationRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collabration': {
      id: '/collabration'
      path: '/collabration'
      fullPath: '/collabration'
      preLoaderRoute: typeof CollabrationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/collabration/_auth/sign-in': {
      id: '/collabration/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/collabration/sign-in'
      preLoaderRoute: typeof CollabrationAuthSignInRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
    '/collabration/_auth/otp': {
      id: '/collabration/_auth/otp'
      path: '/otp'
      fullPath: '/collabration/otp'
      preLoaderRoute: typeof CollabrationAuthOtpRouteImport
      parentRoute: typeof CollabrationRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CollabrationRouteRouteChildren {
  CollabrationAuthOtpRoute: typeof CollabrationAuthOtpRoute
  CollabrationAuthSignInRoute: typeof CollabrationAuthSignInRoute
}

const CollabrationRouteRouteChildren: CollabrationRouteRouteChildren = {
  CollabrationAuthOtpRoute: CollabrationAuthOtpRoute,
  CollabrationAuthSignInRoute: CollabrationAuthSignInRoute,
}

const CollabrationRouteRouteWithChildren =
  CollabrationRouteRoute._addFileChildren(CollabrationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CollabrationRouteRoute: CollabrationRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
